# Generated by Django 5.0.1 on 2024-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_animalcard_kind_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='Комментарий'),
        ),
    ]
