# Generated by Django 5.0.1 on 2024-03-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_gender_alter_animalcard_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicecard',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gender', verbose_name='Пол'),
        ),
    ]
