# Generated by Django 5.0.1 on 2024-03-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_advicecard_gender_alter_animalcard_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicecard',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.gender', verbose_name='Пол'),
        ),
    ]
