# Generated by Django 5.0.2 on 2024-04-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_calendar_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcard',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.mission', verbose_name='Цель'),
        ),
    ]
